name: copy_gen
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.6

# Add regular dependencies here.
dependencies:
  build: ^2.4.1

dev_dependencies:
  build_runner: ^2.4.6
  test: ^1.23.3
