name: copy_gen_for_annotation
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  analyzer: ^6.1.0
  build: ^2.4.1
  copy_gen_annotation:
    path: ../copy_gen_annotation

dev_dependencies:
  build_runner: ^2.4.6
  test: ^1.23.3
